Feat/login auth
klavenjones/open-forum-backend pull request #14
Opened 2022-12-13 16:43 UTC by klavenjones

## What?
Added support for login using the Passport Local strategy. This PR relates to this [ticket](https://trello.com/c/fxMLtKYl)

- Added Passport and used the local passport strategy to aid in user authorization
- Created Login service, modules, and controller 
- Add getUserbyUsername to the user.service, to help retrieve user.

2022-12-13 16:56 UTC, kaitwalla requested changes

2022-12-13 16:56 UTC, kaitwalla commented on src/api/auth/login/login.controller.spec.ts
> +  describe('login', () => {
Needs failed logins as well

2022-12-13 16:56 UTC, kaitwalla commented on src/api/auth/login/login.service.spec.ts
> +    it('should call userService.getUserByUsername atleast once.', async () => {
What is this actually testing? Your other test names describe what is happening ("should return null when password does not match"), this is just describing the expect using the same terms

2022-12-13 16:56 UTC, kaitwalla commented on src/api/user/user.service.spec.ts
> +  describe('getUserByUsername', () => {
You did a good job with these. These are hard tests to write because so much of this is abstracted by the library code. If I were writing these from scratch, I might also consider testing the outcomes (findByOne returns user when proper params are passed; returns null or w/e when not). I don't know that it's required here because of the library code, but for me it would bring peace of mind because if the outcome changes, your automated tests would catch it.

2022-12-13 16:56 UTC, kaitwalla commented on src/api/user/user.service.spec.ts
> +  describe('getUserByUsername', () => {
Also, from a TDD perspective, outcomes are more useful than calledWIth in this scenario because it could use the proper params but still not provide proper functionality.

2022-12-13 21:06 UTC, klavenjones commented on src/api/auth/login/login.service.spec.ts
> +    it('should call userService.getUserByUsername atleast once.', async () => {
@kaitwalla I was trying to test if the service was being called correctly inside the controller.

2022-12-13 21:24 UTC, klavenjones commented on src/api/auth/login/login.controller.spec.ts
> +  describe('login', () => {
@kaitwalla Should I attempt to mock these guards to test an unauthorized user (There will be more guards down the line)? Or could I rely on the e2e tests to test for proper requests?

2022-12-14 17:38 UTC, kaitwalla commented on src/api/auth/login/login.controller.spec.ts
> +  describe('login', () => {
My goal was to unit-test the login controller, but it appears that logic gets tested (in Nest) at the Login service level, which you already did. Nicely done.

2022-12-14 17:42 UTC, kaitwalla approved these changes

2022-12-14 17:57 UTC, merged